# Generated by Django 5.2.8 on 2025-11-24 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
