# Generated by Django 5.2.8 on 2025-11-27 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_remove_post_comment_count_remove_post_like_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postimage',
            name='caption',
        ),
    ]
