# Generated by Django 5.2.8 on 2025-11-17 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailotp',
            name='purpose',
        ),
    ]
