# Generated by Django 5.2.8 on 2025-11-19 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_user_job_role_passwordresettoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='job_role',
            field=models.CharField(choices=[('employee', 'Employee'), ('employer', 'Employer'), ('company', 'Company')], default='employee', max_length=10),
        ),
    ]
