# Generated by Django 5.2.8 on 2025-11-20 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_profile_bio_profile_image_alter_profile_user_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('fulltime', 'Full time'), ('parttime', 'Part time'), ('intern', 'Intern')], default='fulltime', max_length=20),
        ),
    ]
