# Generated by Django 5.2.8 on 2025-11-20 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_job_deleted_at_alter_job_job_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='responsibilities',
            new_name='requirments',
        ),
    ]
