# Generated by Django 5.2.8 on 2025-11-20 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_responsibilities_job_requirments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='profiles/%Y/%m/%d/')),
                ('website', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
