# Generated by Django 5.2.8 on 2025-11-21 06:28

from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='user',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='company',
                to=settings.AUTH_USER_MODEL,
                null=True
            ),
        ),
    ]
