# Generated by Django 5.2.8 on 2025-11-21 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_company_company_name_alter_company_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
