# Generated by Django 5.2.8 on 2025-11-22 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_company_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='skills',
        ),
        migrations.DeleteModel(
            name='Job',
        ),
    ]
