# Generated by Django 5.2.8 on 2025-11-22 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_profile_user_companyprofile_userprofile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='company_name',
        ),
    ]
