# Generated by Django 5.2.8 on 2025-11-27 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_follow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='status',
        ),
        migrations.RemoveField(
            model_name='follow',
            name='updated_at',
        ),
    ]
