# Generated by Django 5.2.8 on 2025-12-15 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_remove_follow_status_remove_follow_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='company_name',
            field=models.CharField(blank=True, help_text='Only for employers', max_length=255, null=True),
        ),
    ]
