# Generated by Django 5.2.8 on 2025-12-27 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_follow_status_follow_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='company_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
